name: Deploy Space Portfolio

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create vendor and font directories
        run: mkdir -p js/vendor static/fonts public/js/vendor public/static/fonts

      - name: Download Three.js core
        run: curl -L -o js/vendor/three.module.js https://unpkg.com/three@0.159.0/build/three.module.js

      - name: Download OrbitControls
        run: curl -L -o js/vendor/OrbitControls.js https://unpkg.com/three@0.159.0/examples/jsm/controls/OrbitControls.js

      - name: Download FontLoader
        run: curl -L -o js/vendor/FontLoader.js https://unpkg.com/three@0.159.0/examples/jsm/loaders/FontLoader.js

      - name: Download TextGeometry
        run: curl -L -o js/vendor/TextGeometry.js https://unpkg.com/three@0.159.0/examples/jsm/geometries/TextGeometry.js

      - name: Download WebFontLoader
        run: curl -L -o js/vendor/webfontloader.js https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js

      - name: Download helvetiker font
        run: curl -L -o static/fonts/helvetiker_regular.typeface.json https://unpkg.com/three@0.159.0/examples/fonts/helvetiker_regular.typeface.json

      - name: Copy project files to public directory (excluding itself)
        run: |
          mkdir public
          rsync -av --exclude='public' ./ public/
          mkdir -p public/js/vendor public/static/fonts
          cp -r js/vendor/* public/js/vendor/
          cp -r static/fonts/* public/static/fonts/
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4