name: Fetch GitHub Repositories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch GitHub repos for willyh15
        run: |
          curl -s "https://api.github.com/users/willyh15/repos?per_page=100&type=owner&sort=updated" \
            | jq '[.[] | { name, html_url, description, language, topics, homepage, stargazers_count, forks_count, pushed_at }]' \
            > static/repos.json

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add static/repos.json
          git commit -m "🔄 Auto-update repos.json"
          git push